FarmaKami18/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('apotek/', include(('apotek.urls', 'apotek'), namespace='apotek')),
    path('alat_medis/', include(('alat_medis.urls', 'alat_medis'), namespace='alat_medis')),
    path('list_produk_dibeli/', include(('list_produk_dibeli.urls', 'list_produk_dibeli'), namespace='list_produk_dibeli')),
    path('pengantaran_farmasi/', include(('pengantaran_farmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('produk_apotek/', include(('produk_apotek.urls', 'produk_apotek'), namespace='produk_apotek')),
    path('transaksi_resep/', include(('transaksi_resep.urls', 'transaksi_resep'), namespace='transaksi_resep')),
    path('transaksi_pembelian/', include(('transaksi_pembelian.urls', 'transaksi_pembelian'), namespace='transaksi_pembelian')),
]

apotek/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:id_apotek>/edit/', views.edit, name='edit'),
    path('<str:id_apotek>/delete/', views.delete, name='delete')
]

authentication/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/konsumen/', views.register_konsumen, name='register_konsumen'),
    path('register/cs/', views.register_cs, name='register_cs'),
    path('register/admin_apotek/', views.register_admin, name='register_admin'),
    path('register/kurir', views.register_kurir, name='register_kurir'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout')
]

authentication/models.py
from django.db import models, connection
from converter.fetch_to_dict import dictfetchall
# Create your models here.

def fetch_all_apoteker():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM apoteker")
    return dictfetchall(cursor)

def fetch_all_pengguna():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM pengguna")
    return dictfetchall(cursor)

def get_pengguna_from_specific_table(table_name ,email):
    cursor = connection.cursor()
    if str.lower(table_name) == 'pengguna':
        cursor.execute("SELECT * FROM PENGGUNA WHERE email = %s", [email])
    elif str.lower(table_name) == 'cs':
        cursor.execute("SELECT * FROM CS WHERE email = %s", [email])
    elif str.lower(table_name) == 'konsumen':
        cursor.execute("SELECT * FROM KONSUMEN WHERE email = %s", [email])
    elif str.lower(table_name) == 'admin_apotek':
        cursor.execute("SELECT * FROM ADMIN_APOTEK WHERE email = %s", [email])
    else:
        cursor.execute("SELECT * FROM KURIR WHERE email = %s", [email])
    pengguna = dictfetchall(cursor)
    return pengguna

def get_biggest_id_on_specific_table(table_name):
    cursor = connection.cursor()
    if str.lower(table_name) == 'konsumen':
        cursor.execute("SELECT * FROM KONSUMEN ORDER BY id_konsumen DESC LIMIT 1")
        if konsumen := cursor.fetchone():
            return konsumen[0]
        else:
            return '0'
    elif str.lower(table_name) == 'kurir':
        cursor.execute("SELECT * FROM KURIR ORDER BY id_kurir DESC LIMIT 1")
        if kurir := cursor.fetchone():
            return kurir[0]
        else:
            return '0'
    else:
        return 'not_found'


def insert_pengguna_with_role(table_name, data):
    cursor = connection.cursor()
    cursor.execute("INSERT INTO PENGGUNA VALUES (%s, %s, %s, %s)", [data['email'],data['telepon'],data['password'],data['nama']])
    if str.lower(table_name) == 'admin_apotek':
        cursor.execute("INSERT INTO APOTEKER VALUES (%s)", [data['email']])
        cursor.execute("INSERT INTO ADMIN_APOTEK VALUES (%s, NULL)", [data['email']])
        return
    elif str.lower(table_name) == 'cs':
        cursor.execute("INSERT INTO APOTEKER VALUES (%s)", [data['email']])
        cursor.execute("INSERT INTO CS VALUES (%s, %s, %s)", [data['no_ktp'], data['email'], data['no_sia']])
        return
    elif str.lower(table_name) == 'konsumen':
        cursor.execute("INSERT INTO KONSUMEN VALUES (%s, %s, %s, %s)", [data['id_konsumen'], data['email'], data['sex'], data['tanggalLahir']])
        for statusAlamat, namaAlamat in data['alamats']:
            cursor.execute("INSERT INTO ALAMAT_KONSUMEN VALUES (%s, %s, %s)", [data['id_konsumen'], namaAlamat, statusAlamat])
        return
    elif str.lower(table_name) == 'kurir':
        cursor.execute("INSERT INTO KURIR VALUES (%s, %s, %s)", [data['id_kurir'], data['email'], data['perusahaan']])
    else:
        return

authentication/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import QueryDict
from .models import *

# Create your views here.

#TO DO : Benerin returnnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
def index(request):
    if(request.session.get('user') is None):
        return render(request, 'authentication/index.html')
    else:
        return redirect('authentication:profile')

#TO DO : check sesaikan dengan pdf
def register(request):
    if(request.session.get('user') is None):
        return render(request,'authentication/register.html')
    else:
        return redirect('authentication:profile')

def register_konsumen(request):
    data = {}
    if (request.method == 'GET'):
        if (request.session.get('user') is None):
            return render(request,'authentication/register_konsumen.html', data)
        else:
            return redirect('authentication:profile')
    else:
        current_biggest_id_konsumen = get_biggest_id_on_specific_table('konsumen')
        current_biggest_id_konsumen_number = ''.join(filter(str.isdigit, current_biggest_id_konsumen))
        current_biggest_id_konsumen_alphabet = current_biggest_id_konsumen.strip(current_biggest_id_konsumen_number)
        new_konsumen_id_number = int(current_biggest_id_konsumen_number) + 1

        data['email'] = request.POST['email']
        data['password'] = request.POST['password']
        data['telepon'] = request.POST['telepon']
        data['nama'] = request.POST['nama']
        data['sex'] = request.POST['sex']
        data['tanggalLahir'] = request.POST['tanggalLahir']
        data['alamats'] = list(zip(request.POST.getlist('statusAlamat', []), request.POST.getlist('namaAlamat', [])))
        data['id_konsumen'] = current_biggest_id_konsumen_alphabet + str(new_konsumen_id_number)

        if(any(get_pengguna_from_specific_table('PENGGUNA', data['email']))):
            return render(request, 'authentication/register_konsumen.html', data)
        else:
            insert_pengguna_with_role('konsumen', data)
            pengguna = get_pengguna_from_specific_table('PENGGUNA', data['email'])[0]
            pengguna['role'] = 'konsumen'
            request.session['user'] = pengguna
            return redirect('apotek:index')

def register_cs(request):
    data = {}
    if (request.method == 'GET'):
        if (request.session.get('user') is None):
            return render(request,'authentication/register_cs.html', data)
        else:
            return redirect('authentication:profile')
    else:
        data['email'] = request.POST['email']
        data['password'] = request.POST['password']
        data['telepon'] = request.POST['telepon']
        data['nama'] = request.POST['nama']
        data['no_ktp'] = request.POST['ktp']
        data['no_sia'] = request.POST['sia']

        if(any(get_pengguna_from_specific_table('PENGGUNA', data['email']))):
            return render(request, 'authentication/register_cs.html', data)
        else:
            insert_pengguna_with_role('cs', data)
            pengguna = get_pengguna_from_specific_table('PENGGUNA', data['email'])[0]
            pengguna['role'] = 'cs'
            request.session['user'] = pengguna
            return redirect('apotek:index')

def register_kurir(request):
    data = {}
    if (request.method == 'GET'):
        if (request.session.get('user') is None):
            return render(request,'authentication/register_kurir.html', data)
        else:
            return redirect('authentication:profile')
    else:
        current_biggest_id_kurir = get_biggest_id_on_specific_table('kurir')
        current_biggest_id_kurir_number = ''.join(filter(str.isdigit, current_biggest_id_kurir))
        current_biggest_id_kurir_alphabet = current_biggest_id_kurir.strip(current_biggest_id_kurir_number)
        new_kurir_id_number = int(current_biggest_id_kurir_number) + 1

        data['email'] = request.POST['email']
        data['password'] = request.POST['password']
        data['telepon'] = request.POST['telepon']
        data['nama'] = request.POST['nama']
        data['perusahaan'] = request.POST['perusahaan']
        data['id_kurir'] = current_biggest_id_kurir_alphabet + str(new_kurir_id_number)

        if(any(get_pengguna_from_specific_table('PENGGUNA', data['email']))):
            return render(request, 'authentication/register_kurir.html', data)
        else:
            insert_pengguna_with_role('kurir', data)
            pengguna = get_pengguna_from_specific_table('PENGGUNA', data['email'])[0]
            pengguna['role'] = 'kurir'
            request.session['user'] = pengguna
            return redirect('apotek:index')

def register_admin(request):
    data = {}
    if (request.method == 'GET'):
        if (request.session.get('user') is None):
            return render(request,'authentication/register_admin_apotek.html', data)
        else:
            return redirect('authentication:profile')
    else:
        data['email'] = request.POST['email']
        data['password'] = request.POST['password']
        data['telepon'] = request.POST['telepon']
        data['nama'] = request.POST['nama']

        if(any(get_pengguna_from_specific_table('PENGGUNA', data['email']))):
            return render(request, 'authentication/register_admin_apotek.html', data)
        else:
            insert_pengguna_with_role('admin_apotek', data)
            pengguna = get_pengguna_from_specific_table('PENGGUNA', data['email'])[0]
            pengguna['role'] = 'admin_apotek'
            request.session['user'] = pengguna
            return redirect('apotek:index')

def profile(request):
    data = {}
    if(request.method == 'GET') & (request.session.get('user') is not None):
        pengguna = get_pengguna_from_specific_table('PENGGUNA', request.session['user']['email'])[0]
        return render(request, 'authentication/profile.html', pengguna)
    else:
        return redirect('authentication:index')

def login(request):
    data = {}
    if(request.method == 'GET'):
        if (request.session.get('user') is None):
            return render(request, 'authentication/login.html', data)
        else:
            return redirect('authentication:profile')
    else:
        data['email'] = request.POST['email']
        data['password'] = request.POST['password']

        if any(get_pengguna_from_specific_table('PENGGUNA', data['email'])):
            pengguna = get_pengguna_from_specific_table('PENGGUNA', data['email'])[0]
            if data['password'] == pengguna['password']:

                if any(get_pengguna_from_specific_table('konsumen', data['email'])):
                    pengguna['role'] = 'konsumen'
                elif any(get_pengguna_from_specific_table('cs', data['email'])):
                    pengguna['role'] = 'cs'
                elif any(get_pengguna_from_specific_table('kurir', data['email'])):
                    pengguna['role'] = 'kurir'
                elif any(get_pengguna_from_specific_table('admin_apotek', data['email'])):
                    pengguna['role'] = 'admin_apotek'
                else:
                    pengguna['role'] = 'not_set'
                request.session['user'] = pengguna
                return redirect('apotek:index')

            else:
                return render(request, 'authentication/login.html', data)
        else:
            return render(request, 'authentication/login.html', data)

def logout(request):
    if(request.method == 'POST'):
        request.session.flush()
        return redirect('authentication:index')
    else:
        return HttpResponse('Only POST request available for LOGOUT')

authentication/templates/authentication/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Dashboard {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/dashboard.css' %}">
{% endblock %}

{% block nav %}
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
<div class="dashboard">
    <h2>Farma Kami</h2>
    <h4>Apotek Terbaik Se-Dunia</h4>
    <div class="buttons">
        <a href="{% url 'authentication:login' %}" class="btn btn-primary">Login</a>
        <a href="{% url 'authentication:register' %}" class="btn btn-primary">Register</a>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'base.html'%}

{% block title %}
Login
{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form method="POST" action="{% url 'authentication:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail">Email address</label>
                <input type="email" class="form-control" id="inputEmail" name="email" value="{{ email }}">
            </div>
            <div class="form-group">
                <label for="inputPassword">Password</label>
                <input type="password" class="form-control" name="password" id="inputPassword">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/profile.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'js/authentication/profile.js' %}"></script>
{% endblock %}

{% block title %} Profile   {% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="card"">
            <img src="{% static 'icons/face.svg' %}" class="card-img-top" >
            <div class="card-body">
                <h5 class="card-title">
                    Email
                </h5>
                <p>
                    {{ email }}
                </p>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    Role
                </h5>
                <p>
                    {{ request.session.user.role }}
                </p>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    Telepon
                </h5>
                <p>
                    {{ request.session.user.telepon }}
                </p>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    Nama Lengkap
                </h5>
                <p>
                    {{ request.session.user.nama_lengkap }}
                </p>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/register.css' %}">
{% endblock %}

{% block nav %}{% endblock %}

{% block header %}
<div class="header">
    <h3>
        Ingin mendaftar sebagai apa?
    </h3>
</div>
{% endblock %}

{% block title %} Daftar {% endblock %}

{% block content %}

<div class="role-container">
    <div class="card-deck">
        <div class="card">
            <img src="{% static 'icons/medical-team.svg' %}" class="card-img-top" alt="Admin Apotek">
            <div class="card-body">
                <h5 class="card-title">Admin Apotek</h5>
                <a href="{% url 'authentication:register_admin' %}" class="btn btn-primary" >Register</a>
            </div>
        </div>
        <div class="card">
            <img src="{% static 'icons/cs.svg' %}" class="card-img-top" alt="Customer Service">
            <div class="card-body">
                <h5 class="card-title">Customer Service</h5>
                <a href="{% url 'authentication:register_cs' %}" class="btn btn-primary">Register</a>
            </div>
        </div>
        <div class="card">
            <img src="{% static 'icons/customer.svg' %}" class="card-img-top" alt="Konsumen">
            <div class="card-body">
                <h5 class="card-title">Konsumen</h5>
                <a href="{% url 'authentication:register_konsumen' %}" class="btn btn-primary">Register</a>
            </div>
        </div>
        <div class="card">
            <img src="{% static 'icons/courier.svg' %}" class="card-img-top" alt="Kurir">
            <div class="card-body">
                <h5 class="card-title">Kurir</h5>
                <a href="{% url 'authentication:register_kurir' %}" class="btn btn-primary">Register</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/register_admin_apotek.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Daftar Admin Apotek
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'authentication:register' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM PENDAFTARAN ADMIN APOTEK</h3>
</div>
<form method="POST" action="{% url 'authentication:register_admin' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" name="email" class="form-control" id="inputEmail" required aria-describedby="emailHelp" value="{{ email }}">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" name="password" class="form-control" id="inputPassword" required>
    </div>
    <div class="form-group">
        <label for="inputNamaLengkap">Nama Lengkap</label>
        <input type="text" name="nama" class="form-control" id="inputNamaLengkap" required placeholder="ex: Joko Susilo" value="{{ nama }}">
    </div>
    
    <div class="form-group">
        <label for="inputNomorTelp">Nomor Telepon</label>
        <input type="number" name="telepon" class="form-control" id="inputNomorTelp" required placeholder="ex: 081212121212" value="{{ telepon }}">
    </div>
    <button type="submit" class="btn btn-primary btn-block">DAFTAR</button>
</form>
{% endblock %}

authentication/templates/authentication/register_cs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Daftar CS
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'authentication:register' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM PENDAFTARAN CS</h3>
</div>
<form method="POST" action="{% url 'authentication:register_cs' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" name="email" class="form-control" id="inputEmail" required aria-describedby="emailHelp" value="{{ email }}">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" name="password" class="form-control" id="inputPassword" required>
    </div>
    <div class="form-group">
        <label for="inputNamaLengkap">Nama Lengkap</label>
        <input type="text" name="nama" class="form-control" id="inputNamaLengkap" required placeholder="ex: Joko Susilo" value="{{ nama }}">
    </div>
    
    <div class="form-group">
        <label for="inputNomorTelp">Nomor Telepon</label>
        <input type="number" name="telepon" class="form-control" id="inputNomorTelp" required placeholder="ex: 081212121212" value="{{ telepon }}">
    </div>

    <div class="form-group">
        <label for="inputNomorKtp">Nomor KTP</label>
        <input type="number" name="ktp" class="form-control" id="inputNomorKtp" required placeholder="ex: 3271046504930000" value="{{ ktp }}">
    </div>

    <div class="form-group">
        <label for="inputNomorSia">Nomor SIA</label>
        <input type="number" name="sia" class="form-control" id="inputNomorSia" required placeholder="ex: 1111111111" value="{{ sia }}">
    </div>

    <button type="submit" class="btn btn-primary btn-block">DAFTAR</button>
</form>
{% endblock %}

authentication/templates/authentication/register_konsumen.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Daftar Konsumen
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'js/date_init.js' %}"></script>
<script src="{% static 'js/authentication/main.js' %}"></script>
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'authentication:register' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM PENDAFTARAN KONSUMEN</h3>
</div>
<form method="POST" action="{% url 'authentication:register_konsumen' %}">
    {% csrf_token %}

    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" name="email" class="form-control" id="inputEmail" placeholder="ex: mail@gmail.com" aria-describedby="emailHelp" value="{{ email }}">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" name="password" class="form-control" id="inputPassword">
    </div>

    <div class="form-group">
        <label for="inputNamaLengkap">Nama Lengkap</label>
        <input type="text" name="nama" class="form-control" id="inputNamaLengkap" placeholder="ex: Joko Susilo" value="{{ nama }}">
    </div>
    
    <div class="form-group">
        <label for="inputNomorTelp">Nomor Telepon</label>
        <input type="number" name="telepon" class="form-control" id="inputNomorTelp" placeholder="ex: 081212121212" value="{{ telepon }}">
    </div>
    
    <label for="inputGroupSex">
        Jenis Kelamin
    </label>
    <div class="form-group" id="inputGroupSex">
        <div class="form-check form-check-inline">
            <input {% if sex == "L" %} checked {% else %} checked {% endif %} class="form-check-input" type="radio" name="sex" id="sexRadio1" value="L">
            <label class="form-check-label" for="sexRadio1">L</label>
        </div>
        
        <div class="form-check form-check-inline">
            <input {% if sex == "P" %}checked {% endif %} class="form-check-input" type="radio" name="sex" id="sexRadio2" value="P">
            <label class="form-check-label" for="sexRadio2">P</label>
        </div>
    </div>


    <div class="form-group">
        <label for="inputTanggalLahir">Tanggal Lahir</label>
        <input type="text" readonly name="tanggalLahir" class="form-control date-picker" id="inputTanggalLahir" value="{{ tanggalLahir }}">
    </div>

    <label for="alamatGroup">
        Alamat
    </label>
    <div class="form-group" id="alamatGroup">
        {% if alamats %}
            {% for statusAlamat, namaAlamat in alamats %}
            <div id="inputGroupAlamat">
                <div class="form-group">
                    <div class="input-group status-alamat">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                Status & Detail Alamat
                            </span>
                        </div>
                        <input type="text" name="statusAlamat" aria-label="Status alamat" placeholder="ex: Terkonfirmasi" class="form-control" value="{{ statusAlamat }}">
                        <input type="text" name="namaAlamat" aria-label="Nama alamat" placeholder="ex: Jl. Cikapundung No.12, Bandung" class="form-control" value="{{ namaAlamat }}">
                        <div class="input-group-append">
                            <button type="button" onclick="removeAlamat(this)" class="btn btn-danger hapus-alamat">X</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div id="inputGroupAlamat">
                <div class="form-group">
                    <div class="input-group status-alamat">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                Status & Detail Alamat
                            </span>
                        </div>
                        <input type="text" name="statusAlamat" aria-label="Status alamat" placeholder="ex: Terkonfirmasi" class="form-control" >
                        <input type="text" name="namaAlamat" aria-label="Nama alamat" placeholder="ex: Jl. Cikapundung No.12, Bandung" class="form-control" >
                        <div class="input-group-append">
                            <button type="button" onclick="removeAlamat(this)" class="btn btn-danger hapus-alamat">X</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        
        <button type="button" id="tambahAlamat" class="btn btn-success btn-block">Tambah alamat</button>
    </div>

    <button type="submit" class="btn btn-primary btn-block">DAFTAR</button>
</form>
{% endblock %}

authentication/templates/authentication/register_kurir.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Daftar Kurir
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'authentication:register' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM PENDAFTARAN KURIR</h3>
</div>
<form method="POST" action="{% url 'authentication:register_kurir' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputEmail">Email address</label>
        <input type="email" name="email" class="form-control" id="inputEmail" required aria-describedby="emailHelp" value="{{ email }}">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" name="password" class="form-control" id="inputPassword" required>
    </div>
    <div class="form-group">
        <label for="inputNamaLengkap">Nama Lengkap</label>
        <input type="text" name="nama" class="form-control" id="inputNamaLengkap" required placeholder="ex: Joko Susilo" value="{{ nama }}">
    </div>
    
    <div class="form-group">
        <label for="inputNomorTelp">Nomor Telepon</label>
        <input type="number" name="telepon" class="form-control" id="inputNomorTelp" required placeholder="ex: 081212121212" value="{{ telepon }}">
    </div>

    <div class="form-group">
        <label for="inputNamaPerusahaan">Nama Perusahaan</label>
        <input type="text" name="perusahaan" class="form-control" id="inputNamaPerusahaan" required placeholder="ex: Makmur Jaya" value="{{ perusahaan }}">
    </div>

    <button type="submit" class="btn btn-primary btn-block">DAFTAR</button>
</form>
{% endblock %}