FarmaKami18/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('apotek/', include(('apotek.urls', 'apotek'), namespace='apotek')),
    path('alat_medis/', include(('alat_medis.urls', 'alat_medis'), namespace='alat_medis')),
    path('list_produk_dibeli/', include(('list_produk_dibeli.urls', 'list_produk_dibeli'), namespace='list_produk_dibeli')),
    path('pengantaran_farmasi/', include(('pengantaran_farmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('produk_apotek/', include(('produk_apotek.urls', 'produk_apotek'), namespace='produk_apotek')),
    path('transaksi_resep/', include(('transaksi_resep.urls', 'transaksi_resep'), namespace='transaksi_resep')),
    path('transaksi_pembelian/', include(('transaksi_pembelian.urls', 'transaksi_pembelian'), namespace='transaksi_pembelian')),
]

alat_medis/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<str:id_alat_medis>/edit/', views.edit, name='edit'),
    path('<str:id_alat_medis>/delete/', views.delete, name='delete')
]

apotek/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:id_apotek>/edit/', views.edit, name='edit'),
    path('<str:id_apotek>/delete/', views.delete, name='delete')
]

alat_medis/models.py
from django.db import models, connection
from converter.fetch_to_dict import dictfetchall
# Create your models here.

def fetch_all_alat_medis():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM alat_medis")
    return dictfetchall(cursor)

def get_biggest_produk_id():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM PRODUK ORDER BY id_produk DESC LIMIT 1")
    produk = cursor.fetchone()
    return produk[0]

def get_biggest_alat_medis_id():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM ALAT_MEDIS ORDER BY id_alat_medis DESC LIMIT 1")
    alat_medis = cursor.fetchone()
    return alat_medis[0]

def get_alat_medis(id_alat_medis):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM ALAT_MEDIS WHERE id_alat_medis = %s", [id_alat_medis])
    return dictfetchall(cursor)

def insert_produk(id_produk):
    cursor = connection.cursor()
    cursor.execute("INSERT INTO PRODUK VALUES (%s)", [id_produk])
    return

def insert_alat_medis(data):
    cursor = connection.cursor()
    cursor.execute("INSERT INTO ALAT_MEDIS VALUES (%s, %s, %s, %s, %s)", 
    [
        data['idAlatMedis'], data['namaAlatMedis'], data['deskripsiAlat'], data['jenisPenggunaan'], data['idProduk']
    ])
    return

def update_alat_medis(data):
    cursor = connection.cursor()
    cursor.execute("UPDATE ALAT_MEDIS SET "+
    "nama_alat_medis = %s, deskripsi_alat = %s, jenis_penggunaan = %s "+
    "WHERE id_alat_medis = %s",
    [
        data['namaAlatMedis'], data['deskripsiAlat'], data['jenisPenggunaan'], data['idAlatMedis']
    ])

def delete_produk(id_produk):
    cursor = connection.cursor()
    cursor.execute("DELETE FROM PRODUK WHERE id_produk= %s", [id_produk])

def delete_alat_medis(id_alat_medis):
    cursor = connection.cursor()
    cursor.execute("DELETE FROM ALAT_MEDIS WHERE id_alat_medis = %s", [id_alat_medis])

alat_medis/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *

# Create your views here.

def index(request):
    data = {}
    if request.session.get('user') is not None:
        data['alat_medis'] = fetch_all_alat_medis()
        return render(request,'alat_medis/index.html', data)
    else:
        return redirect('authentication:index')

#TO DO : cek sesuaikan dengan pdf
def create(request):
    data = {}
    if request.session.get('user') is not None:
        if (request.session['user']['role'] == 'admin_apotek') or (request.session['user']['role'] == 'cs'):
            if request.method == 'GET':
                return render(request,'alat_medis/create.html')
            else:
                current_biggest_alat_medis_id = get_biggest_alat_medis_id()
                current_biggest_alat_medis_id_number = ''.join(filter(str.isdigit, current_biggest_alat_medis_id))
                current_biggest_alat_medis_id_alphabet = current_biggest_alat_medis_id.strip(current_biggest_alat_medis_id_number)
                new_alat_medis_id_number = int(current_biggest_alat_medis_id_number) + 1

                data['idAlatMedis'] = current_biggest_alat_medis_id_alphabet + str(new_alat_medis_id_number)
                data['namaAlatMedis'] = request.POST['namaAlatMedis']
                data['deskripsiAlat'] = request.POST['deskripsiAlat']
                data['jenisPenggunaan'] = request.POST['jenisPenggunaan']

                current_biggest_produk_id = get_biggest_produk_id()
                current_biggest_produk_id_number = ''.join(filter(str.isdigit, current_biggest_produk_id))
                current_biggest_produk_id_alphabet = current_biggest_produk_id.strip(current_biggest_produk_id_number)
                new_produk_id_number = int(current_biggest_produk_id_number) + 1
                new_produk_id = current_biggest_produk_id_alphabet + str(new_produk_id_number)

                insert_produk(new_produk_id)
                data['idProduk'] = new_produk_id

                insert_alat_medis(data)
                return redirect('alat_medis:index')
        else:
            return redirect('alat_medis:index')
    else:
        return redirect('authentication:index')

def edit(request, id_alat_medis):
    data = {}
    if request.session.get('user') is not None:
        if (request.session['user']['role'] == 'admin_apotek') or (request.session['user']['role'] == 'cs'):
            if request.method == 'GET':
                if any(alat_medis:= get_alat_medis(id_alat_medis)):
                    data = alat_medis[0]
                    return render(request,'alat_medis/edit.html', data)
                else:
                    return redirect('alat_medis:index')
            else:
                data['idAlatMedis'] = id_alat_medis
                data['namaAlatMedis'] = request.POST['namaAlatMedis']
                data['deskripsiAlat'] = request.POST['deskripsiAlat']
                data['jenisPenggunaan'] = request.POST['jenisPenggunaan']

                update_alat_medis(data)
                return redirect('alat_medis:index')
        else:
            return redirect('alat_medis:index')
    else:
        return redirect('authentication:index')

def delete(request, id_alat_medis):
    if request.session.get('user') is not None:
        if (request.session['user']['role'] == 'admin_apotek') or (request.session['user']['role'] == 'cs'):
            if request.method == 'POST':
                alat_medis = get_alat_medis(id_alat_medis)[0]
                delete_alat_medis(alat_medis['id_alat_medis'])
                delete_produk(alat_medis['id_produk'])
        return redirect('alat_medis:index')
    else:
        return redirect('authentication:index')

alat_medis/templates/alat_medis/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Create Alat Medis
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'alat_medis:index' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM CREATE ALAT MEDIS</h3>
</div>
<form method="POST" action="{% url 'alat_medis:create' %}">
    {% csrf_token %}

    <div class="form-group">
        <label for="inputNamaAlatMedis">Nama Alat Medis</label>
        <input type="text" name="namaAlatMedis" class="form-control" id="inputNamaAlatMedis" placeholder="ex: Jarum Suntik" >
    </div>

    <div class="form-group">
        <label for="inputDeskripsiAlat">Deskripsi Alat</label>
        <input type="text" name="deskripsiAlat" class="form-control" id="inputDeskripsiAlat" placeholder="ex: Buat nyuntik" >
    </div>

    <div class="form-group">
        <label for="inputJenisPenggunaan">Jenis Penggunaan</label>
        <input type="text" name="jenisPenggunaan" class="form-control" id="inputJenisPenggunaan" placeholder="ex: Disuntik" >
    </div>

    <button type="submit" class="btn btn-primary btn-block">SUBMIT</button>
</form>
{% endblock %}

alat_medis/templates/alat_medis/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Update Alat Medis
{% endblock %}

{% block nav %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/authentication/form_register.css' %}">
{% endblock %}

{% block content %}
<div class="judul">
    <a href="{% url 'alat_medis:index' %}">
        <img src="{% static 'icons/arrow-back.svg' %}" alt="Kembali">
    </a>
    <h3 class="text-center font-weight-bold">FORM UPDATE UPDATE ALAT MEDIS</h3>
</div>
<form method="POST" action="{% url 'alat_medis:edit' id_alat_medis %}">
    {% csrf_token %}

    <div class="form-group">
        <label for="inputIdAlatMedis">ID Alat Medis</label>
        <input type="number" readonly name="idAlatMedis" class="form-control" id="inputIdAlatMedis" value="{{ id_alat_medis }}">
    </div>

    <div class="form-group">
        <label for="inputNamaAlatMedis">Nama Alat Medis</label>
        <input type="text" name="namaAlatMedis" class="form-control" id="inputNamaAlatMedis" placeholder="ex: Jarum Suntik" value="{{ nama_alat_medis }}">
    </div>

    <div class="form-group">
        <label for="inputDeskripsiAlat">Deskripsi Alat</label>
        <input type="text" name="deskripsiAlat" class="form-control" id="inputDeskripsiAlat" placeholder="ex: Buat nyuntik" value="{{ deskripsi_alat }}">
    </div>

    <div class="form-group">
        <label for="inputJenisPenggunaan">Jenis Penggunaan</label>
        <input type="text" name="jenisPenggunaan" class="form-control" id="inputJenisPenggunaan" placeholder="ex: Disuntik" value="{{ jenis_penggunaan }}">
    </div>

    <div class="form-group">
        <label for="inputIdProduk">ID Produk</label>
        <input type="number" readonly name="idProduk" class="form-control" id="inputIdProduk" placeholder="ex: 1" value="{{ id_produk }}">
    </div>

    <button type="submit" class="btn btn-primary btn-block">SUBMIT</button>
</form>
{% endblock %}

alat_medis/templates/alat_medis/index.html
{% extends 'base.html' %}

{% block title %} Alat Medis {% endblock %}

{% block content %}
<div class="alat-medis-container">
        <h1>Alat Medis</h1>
        <table class="table table-light">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID Alat Medis</th>
                    <th scope="col">Nama Alat Medis</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Jenis Penggunaan</th>
                    <th scope="col">ID Produk</th>
                    {% if request.session.user.role == "admin_apotek" or request.session.user.role == "cs" %}
                    <th scope="col">Action</th>
                    {% endif %}
                    
                </tr>
            </thead>
            <tbody>
                {% for am in alat_medis %}
                <tr>
                    <th scope="row">{{ am.id_alat_medis }}</th>
                    <td>{{ am.nama_alat_medis }}</td>
                    <td>{{ am.deskripsi_alat }}</td>
                    <td>{{ am.jenis_penggunaan }}</td>
                    <td>{{ am.id_produk }}</td>
                    {% if request.session.user.role == "admin_apotek" or request.session.user.role == "cs" %}
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{% url 'alat_medis:edit' am.id_alat_medis %}">
                                <button class="btn btn-primary">Update</button>
                            </a>
                            <form action="{% url 'alat_medis:delete' am.id_alat_medis %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}