FarmaKami18/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('apotek/', include(('apotek.urls', 'apotek'), namespace='apotek')),
    path('alat_medis/', include(('alat_medis.urls', 'alat_medis'), namespace='alat_medis')),
    path('list_produk_dibeli/', include(('list_produk_dibeli.urls', 'list_produk_dibeli'), namespace='list_produk_dibeli')),
    path('pengantaran_farmasi/', include(('pengantaran_farmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('produk_apotek/', include(('produk_apotek.urls', 'produk_apotek'), namespace='produk_apotek')),
    path('transaksi_resep/', include(('transaksi_resep.urls', 'transaksi_resep'), namespace='transaksi_resep')),
    path('transaksi_pembelian/', include(('transaksi_pembelian.urls', 'transaksi_pembelian'), namespace='transaksi_pembelian')),
]

apotek/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:id_apotek>/edit/', views.edit, name='edit'),
    path('<str:id_apotek>/delete/', views.delete, name='delete')
]

authentication/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/konsumen/', views.register_konsumen, name='register_konsumen'),
    path('register/cs/', views.register_cs, name='register_cs'),
    path('register/admin_apotek/', views.register_admin, name='register_admin'),
    path('register/kurir', views.register_kurir, name='register_kurir'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout')
]

FarmaKami18/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css%}{% endblock %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/gijgo.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    {% block script %}{% endblock %}
    <title>{% block title  %}{% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        <img src="{% static 'images/dashboard.jpg' %}" alt="">
        {% block nav %}
        <div class="sidebar">
            <div class="card">
                <h3 class="card-header text-center font-weight-bold">
                    Navigasi
                </h3>
                <img style="height: 200px; margin: 0 auto; display: block;" src="{% static 'icons/face.svg' %}" alt="User Image">
                <div class="card-body">
                    <span>Role : {{ request.session.user.role }}</span>
                </div>
                <div class="card-body">
                    <span>Name : {{ request.session.user.nama_lengkap }} </span>
                    <a href="{% url 'authentication:profile' %}" class="text-center btn btn-primary" > Lihat Profil</a>
                </div>
                
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#balaiApotek" role="button" aria-expanded="false" aria-controls="balaiApotek">Balai Pengobatan & Apotek</a>
                    <div class="collapse" id="balaiApotek">
                    {% if request.session.user.role == 'admin_apotek' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'apotek:create' %}"  >Buat Apotek</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'apotek:index' %}" >Daftar Apotek</a>
                    {% if request.session.user.role == 'admin_apotek' %}
                        <a class="text-center btn btn-outline-secondary disabled"  >Buat Balai Pengobatan</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary disabled"  >Daftar Balai Pengobatan</a>
                    </div>
                </div>
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#transaksi" role="button" aria-expanded="false" aria-controls="transaksi"> Transaksi Pembelian / Transaksi Resep</a>
                    <div class="collapse" id="transaksi">
                    {% if request.session.user.role == 'admin_apotek' or request.session.user.role == 'cs' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'transaksi_pembelian:create' %}" >Buat Transaksi Pembelian</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'transaksi_pembelian:index' %}" >Daftar Transaksi Pembelian</a>
                    {% if request.session.user.role == 'admin_apotek' or request.session.user.role == 'cs' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'transaksi_resep:create' %}" >Buat Transaksi Resep</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'transaksi_resep:index' %}" >Daftar Transaksi Resep</a>
                    </div>
                </div>
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#produkApotek" role="button" aria-expanded="false" aria-controls="produkApotek" > Produk-Apotek</a>
                    <div class="collapse" id="produkApotek">
                    {% if request.session.user.role == 'admin_apotek' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'produk_apotek:create' %}" >Buat Produk-Apotek</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'produk_apotek:index' %}" >Daftar Produk-Apotek</a>
                    </div>
                </div>
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#listProduk" role="button" aria-expanded="false" aria-controls="listProduk" > List Produk Dibeli</a>
                    <div class="collapse" id="listProduk">
                    {% if request.session.user.role == 'admin_apotek' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'list_produk_dibeli:create' %}" >Buat List Produk Dibeli</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary"  href="{% url 'list_produk_dibeli:index' %}">Daftar List Produk Dibeli</a>
                    </div>
                </div>
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#pengantaranFarmasi" role="button" aria-expanded="false" aria-controls="pengantaranFarmasi" > Pengantaran Farmasi</a>
                    <div class="collapse" id="pengantaranFarmasi">
                    {% if request.session.user.role == 'admin_apotek' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'pengantaran_farmasi:create' %}" >Buat Pengantaran Farmasi</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'pengantaran_farmasi:index' %}" >Daftar Pengantaran Farmasi</a>
                    </div>
                </div>
                <div class="card-body">
                    <a class="text-center btn btn-secondary parent" data-toggle="collapse" href="#obatAlat" role="button" aria-expanded="false" aria-controls="obatAlat">Obat & Alat Medis</a>
                    <div class="collapse" id="obatAlat">
                    {% if request.session.user.role == 'admin_apotek' or request.session.user.role == 'cs' %}
                        <a class="text-center btn btn-outline-secondary disabled"  >Buat Obat</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary disabled"  >Daftar Obat</a>
                    {% if request.session.user.role == 'admin_apotek' or request.session.user.role == 'cs' %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'alat_medis:create' %}" >Buat Alat Medis</a>
                    {% endif %}
                        <a class="text-center btn btn-outline-secondary" href="{% url 'alat_medis:index' %}" >Daftar Alat Medis</a>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{% url 'authentication:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="text-center btn btn-danger">Keluar</button>
                    </form>
                </div>
            </div>
        </div>
        {% endblock %}
        <div class="container">
            {% block header %}
            <div class="header">
                <img class="burger active" src="{% static 'icons/menu.svg' %}" alt="Navigasi">
                <h3>Farma Kami 18</h3>
            </div>
            {% endblock %}
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
{% block script_footer %}
{% endblock %}
<script>
    $(".burger").click(()=>{
        $(".sidebar").toggleClass("active")
    })
</script>
</html>