FarmaKami18/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('apotek/', include(('apotek.urls', 'apotek'), namespace='apotek')),
    path('alat_medis/', include(('alat_medis.urls', 'alat_medis'), namespace='alat_medis')),
    path('list_produk_dibeli/', include(('list_produk_dibeli.urls', 'list_produk_dibeli'), namespace='list_produk_dibeli')),
    path('pengantaran_farmasi/', include(('pengantaran_farmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('produk_apotek/', include(('produk_apotek.urls', 'produk_apotek'), namespace='produk_apotek')),
    path('transaksi_resep/', include(('transaksi_resep.urls', 'transaksi_resep'), namespace='transaksi_resep')),
    path('transaksi_pembelian/', include(('transaksi_pembelian.urls', 'transaksi_pembelian'), namespace='transaksi_pembelian')),
]

apotek/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:id_apotek>/edit/', views.edit, name='edit'),
    path('<str:id_apotek>/delete/', views.delete, name='delete')
]

transaksi_pembelian/urls.py
from django.urls import path, include
from . import views

#TO DO : Tambahin URLSnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<str:id_transaksi_pembelian>/edit/', views.edit, name='edit'),
    path('<str:id_transaksi_pembelian>/delete/', views.delete, name='delete')
]

transaksi_pembelian/models.py
from django.db import models, connection
from converter.fetch_to_dict import dictfetchall
# Create your models here.

def fetch_all_transaksi_pembelian():
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM transaksi_pembelian")
    return dictfetchall(cursor)

def get_all_id_transaksi_pembelian():
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_transaksi_pembelian FROM TRANSAKSI_PEMBELIAN")
        return [row[0] for row in cursor.fetchall()]

def get_all_id_konsumen_from_konsumen():
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_konsumen FROM KONSUMEN")
        return [row[0] for row in cursor.fetchall()]

def get_id_konsumen(email):
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_konsumen FROM KONSUMEN WHERE email = %s",
        [
            email
        ])
        return [row[0] for row in cursor.fetchall()]

def get_biggest_id_transaksi_pembelian():
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM TRANSAKSI_PEMBELIAN ORDER BY id_transaksi_pembelian DESC LIMIT 1")
        if((tp:=cursor.fetchone()) is not None):
            return tp[0]
        else:
            return '0'

def get_transaksi_pembelian(id_transaksi_pembelian):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM TRANSAKSI_PEMBELIAN WHERE id_transaksi_pembelian = %s",
        [
            id_transaksi_pembelian
        ])
        return dictfetchall(cursor)

def get_transaksi_pembelian_konsumen(id_konsumen):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM TRANSAKSI_PEMBELIAN WHERE id_konsumen = %s",
        [
            id_konsumen
        ])
        return dictfetchall(cursor)

def insert_transaksi_pembelian(data):
    with connection.cursor() as cursor:
        cursor.execute("INSERT INTO TRANSAKSI_PEMBELIAN VALUES(%s, NOW(), 0, %s)", 
        [
            data['id_transaksi_pembelian'], data['id_konsumen']
        ])

def update_transaksi_pembelian(data):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE TRANSAKSI_PEMBELIAN SET " + 
        "waktu_pembelian = NOW(), total_pembayaran = %s, id_konsumen = %s " +
        "WHERE id_transaksi_pembelian = %s", 
        [
            data['total_pembayaran'], data['id_konsumen']
            ,data['id_transaksi_pembelian']
        ])
        return

def delete_transaksi_pembelian(id_transaksi_pembelian):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM TRANSAKSI_PEMBELIAN WHERE id_transaksi_pembelian = %s",
        [
            id_transaksi_pembelian
        ])
        return

transaksi_pembelian/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from .models import *
from datetime import *

# Create your views here.

#TO DO : Benerin returnnya, ikutin aja yang di app AUTHENTICATION / TRANSAKSI RESEP / ALAT MEDIS
def index(request):
    data = {}
    if request.session.get('user') is not None:
        if request.session['user']['role'] == 'konsumen':
            data['transaksi_pembelians'] = get_transaksi_pembelian_konsumen(get_id_konsumen(
                request.session['user']['email'])[0])
        else:
            data['transaksi_pembelians'] = fetch_all_transaksi_pembelian()
        return render(request,'transaksi_pembelian/index.html', data)
    else:
        return redirect('authentication:index')

def create(request):
    data = {}
    if request.session.get('user'):
        if request.session['user']['role'] == 'admin_apotek':
            if request.method == "GET":
                data['id_konsumens'] = get_all_id_konsumen_from_konsumen()
                return render(request,'transaksi_pembelian/create.html', data)
            else:
                current_biggest_id_tp = get_biggest_id_transaksi_pembelian()
                current_biggest_id_tp_number = ''.join(filter(str.isdigit, current_biggest_id_tp))
                current_biggest_id_tp_alphabet = current_biggest_id_tp.strip(current_biggest_id_tp_number)
                new_id_transaksi_pembelian = int(current_biggest_id_tp_number) + 1

                data['id_transaksi_pembelian'] = current_biggest_id_tp_alphabet + str(new_id_transaksi_pembelian)
                data['id_konsumen'] = request.POST['idKonsumen']
                insert_transaksi_pembelian(data)
                return redirect('transaksi_pembelian:index')
        else:
            return redirect('transaksi_pembelian:index')
    else:
        return redirect('authentication:index')

def edit(request, id_transaksi_pembelian):
    data = {}
    if request.session.get('user'):
        if (request.session['user']['role'] == 'admin_apotek'):
            if request.method == "GET":
                if any(transaksi_pembelian := get_transaksi_pembelian(id_transaksi_pembelian)):
                    data['transaksi_pembelian'] = transaksi_pembelian[0]
                    data['id_konsumens'] = get_all_id_konsumen_from_konsumen()
                    return render(request,'transaksi_pembelian/edit.html', data)
                else:
                    return redirect('transaksi_pembelian:index')
            else:
                data['id_transaksi_pembelian'] = id_transaksi_pembelian
                data['waktu_pembelian'] = request.POST['waktuPembelian']
                data['total_pembayaran'] = request.POST['totalPembayaran']
                data['id_konsumen'] = request.POST['idKonsumen']
                print(data)
                update_transaksi_pembelian(data)
                return redirect('transaksi_pembelian:index')
        else:
            return redirect('transaksi_pembelian:index')
    else:
        return redirect('authentication:index')

def delete(request, id_transaksi_pembelian):
    if request.session.get('user'):
        if request.session['user']['role'] == 'admin_apotek':
            if request.method == 'POST':
                delete_transaksi_pembelian(id_transaksi_pembelian)
        return redirect('transaksi_pembelian:index')
    else:
        return redirect('authentication:index')

transaksi_pembelian/templates/transaksi_pembelian/create.html
{% extends 'base.html' %}

{% block title %} Transaksi Pembelian {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-6">
        <h1 class="display-4">Tambahkan Produk</h1>
    </div>
</div>
<br>
<div class="container">
  <form action="{% url 'transaksi_pembelian:create' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for='input_id_konsumen'>ID Konsumen</label>
      <select name="idKonsumen" id="input_id_konsumen" class="form-control">
        {% for id_konsumen in id_konsumens %}
          <option value="{{ id_konsumen }}">{{ id_konsumen }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="button" style="margin-top:75px">
      <button type="submit" class="btn btn-primary">Tambah</button>
    </div>
    <a href="{% url 'transaksi_pembelian:index' %}">
      <button type="button" class="btn btn-secondary">Batal</button>
    </a>
  </form>
</div>
{% endblock %}

transaksi_pembelian/templates/transaksi_pembelian/edit.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-6">
        <h1 class="display-4">Ubah Transaksi Pembelian</h1>
    </div>
</div>
<br>
<form class="form-horizontal" action="{% url 'transaksi_pembelian:edit' transaksi_pembelian.id_transaksi_pembelian %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="idTransaksi">ID Transaksi</label>
    <input type="text" value="{{ transaksi_pembelian.id_transaksi_pembelian }}" class="form-control" id="idTransaksi" name="idTransaksi" readonly>
  </div>

  <div class="form-group">
    <label for="inputWaktu">Waktu Pembelian</label>
    <input type="text" value="{{ transaksi_pembelian.waktu_pembelian|date:'d F Y H:i:s'}}" class="form-control" id="inputWaktu" name="waktuPembelian" readonly>
  </div>

  <div class="form-group">
    <label for="total">Total Pembayaran</label>         
    <input type="text" class="form-control" id="total" name="totalPembayaran" value="{{ transaksi_pembelian.total_pembayaran }}" name="total" readonly>
  </div>

  <div class="form-group">
    <label for='input_id_konsumen'>ID Konsumen</label>
    <select name="idKonsumen" id="input_id_konsumen" class="form-control">
      {% for id_konsumen in id_konsumens %}
        {% if transaksi_pembelian.id_konsumen == id_konsumen %}
        <option selected value="{{ id_konsumen }}">{{ id_konsumen }}</option>
        {% else %}
        <option value="{{ id_konsumen }}">{{ id_konsumen }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>

  <div class="form-group" style="margin-top:75px;">        
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

<script type="text/javascript" language="javascript">
function GetDateTime() {

    var currentdate = new Date(); 
    var datetime = "Last Sync: " + currentdate.getDate() + "/"
                + (currentdate.getMonth()+1)  + "/" 
                + currentdate.getFullYear() + " " 
                + currentdate.getHours() + ":"  
                + currentdate.getMinutes() + ":" 
                + currentdate.getSeconds();
    document.getElementById('waktu').value = datetime;

}
</script>
{% endblock %}

transaksi_pembelian/templates/transaksi_pembelian/index.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<div class="title" style="margin:25px;">
    <h1>Transaksi Pembelian</h1>
</div>
<div class = "table-responsive-sm">
    <table class="table table-light" style="color:white;">
        <thead class="bg-dark">
        <tr>
            <th scope="col">ID Transaksi</th>
            <th scope="col">Waktu Pembelian</th>
            <th scope="col">Total Pembayaran</th>
            {% if request.session.user.role != "konsumen" %}
                <th scope="col">ID Konsumen</th>
            {% endif %}
            {% if request.session.user.role == "admin_apotek" %}
            <th scope="col">Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody style="color:black;">
        {% if request.session.user.role != "konsumen" %}
            {% for transaksi_pembelian in transaksi_pembelians %}
            <tr>
                <th scope="row">{{ transaksi_pembelian.id_transaksi_pembelian }}</th>
                <td>{{ transaksi_pembelian.waktu_pembelian }}</td>
                <td>{{ transaksi_pembelian.total_pembayaran }}</td>
                <td>{{ transaksi_pembelian.id_konsumen }}</td>
                {% if request.session.user.role == "admin_apotek" %}
                <td>
                    <div class="btn-group btn-group-sm">
                        <a href="{% url 'transaksi_pembelian:edit' transaksi_pembelian.id_transaksi_pembelian %}">
                            <button class="btn btn-primary">Update</button>
                        </a>
                        <form action="{% url 'transaksi_pembelian:delete' transaksi_pembelian.id_transaksi_pembelian %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        {% else %}
            {% for transaksi_pembelian in transaksi_pembelians %}
            <tr>
                <th scope="row">{{ transaksi_pembelian.id_transaksi_pembelian }}</th>
                <td>{{ transaksi_pembelian.waktu_pembelian }}</td>
                <td>{{ transaksi_pembelian.total_pembayaran }}</td>
            </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}